name: Docker

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  docker-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Test Build
        run: |
          python scripts/docker_builder.py