name: Docker

on:
  push:
    branches: [ main ]
    paths:
      - "images/**"
      - "scripts/**"
      - "dodo.py"
      - ".github/workflows/main.yml"

  pull_request:
    branches: [ main ]
    paths:
      - "images/**"
      - "scripts/**"
      - "dodo.py"
      - ".github/workflows/main.yml"

  workflow_dispatch:

jobs:
  docker-pipeline:
    runs-on: ubuntu-latest
    if: >
      !contains(github.event.head_commit.message , 'ci skip') &&
      !contains(github.event.pull_request.title, 'ci skip')
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Set Python-specific environment variables
        run: |
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
          echo "PYTHONUNBUFFERED=TRUE" >> $GITHUB_ENV

      - name: Build stack
        run: |
          doit build

      - name: Run manifests
        run: |
          doit manifest

      - name: Push stack
        if: >
          !contains(github.base_ref , 'test') &&
          !contains(github.base_ref , 'dev')
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          doit push

      - name: Archive artifacts and logs
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            artifacts
            logs
            manifests
