name: Docker

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  docker-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sample step
        run: |
          echo "test"